version: '2.1'

services:
  aleph.engineer.artifactory:
    image: aleph.engineer.artifactory
    build: .
    ports:
      - 8081:8081
    volumes:
      - ${PWD}/data:/var/opt/jfrog/artifactory
    restart: always
